version: "3.7"

services:
    discord-bot:
        build: discord-bot
        restart: always
        depends_on:
            - backend
        environment:
            DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
            API_URL: http://backend:8000

    backend:
        build: backend
        restart: always
        environment:
            DJANGO_SECRET: ${DJANGO_SECRET}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        depends_on:
            - db
        networks:
            - backend-discord
            - backend-db
            - backend-frontend

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        secrets:
            - postgres_password
        user: "postgres"
        restart: always
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "postgres"]
            interval: 3s
            retries: 5
            start_period: 30s
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend-db

    website:
        build: website
        environment:
            API_URL: http://backend:8000
        ports:
            - 3000:3000
        volumes:
            - ./frontend/src:/code/src
            - /project/node_modules
        networks:
            - backend-frontend
        depends_on:
            - backend
        restart: always

volumes:
    postgres_data: {}

networks:
    backend-discord:
    backend-db:
    backend-frontend:
