version: "3.7"

services:
    discord-bot:
        build: discord-bot
        restart: on-failure
        depends_on:
            - backend
        env_file:
            - .env
        environment:
            DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
            API_URL: ${API_URL}
            QUEUE_CHANNEL_ID: ${QUEUE_CHANNEL_ID}
            MATCH_CHANNEL_ID: ${MATCH_CHANNEL_ID}
            LEADERBOARD_CHANNEL_ID: ${LEADERBOARD_CHANNEL_ID}

        networks:
            - backend-discord

    backend:
        build: backend
        hostname: backend
        restart: always
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            - .env
        environment:
            DJANGO_SECRET: ${DJANGO_SECRET}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            DEBUG: ${DEBUG}
        networks:
            - backend-discord
            - backend-db
            - backend-frontend
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/"]
            interval: 30s
            timeout: 10s
            retries: 5

    db:
        image: postgres:latest
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        user: "postgres"
        restart: always
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "postgres"]
            interval: 3s
            retries: 5
            start_period: 30s
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend-db

    website:
        build: website
        env_file:
            - .env
        ports:
            - 80:3000
        volumes:
            - ./frontend/src:/code/src
            - /project/node_modules
        networks:
            - backend-frontend
        depends_on:
            - backend
        restart: always

    tunnel:
        image: cloudflare/cloudflared
        restart: unless-stopped
        command: tunnel run
        environment:
            TUNNEL_TOKEN: ${TUNNEL_TOKEN}
        networks:
            - backend-frontend

volumes:
    postgres_data: {}

networks:
    backend-discord:
    backend-db:
    backend-frontend:
