version: "3.7"

services:
    discord-bot:
        build: discord-bot
        restart: always
        depends_on:
            - backend

    backend:
        build: backend
        restart: always
        environment:
            POSTGRES_HOST: db
        depends_on:
            - db
        networks:
            - backend-discord
            - backend-db
            - backend-frontend

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres # don't do this in production lol
        user: "postgres"
        restart: always
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "example"]
            interval: 3s
            retries: 5
            start_period: 30s
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend-db

    website:
        build: website
        ports:
            - 3000:3000
        volumes:
            - ./frontend/src:/code/src
            - /project/node_modules
        networks:
            - backend-frontend
        depends_on:
            - backend
        restart: always

volumes:
    postgres_data: {}

networks:
    backend-discord:
    backend-db:
    backend-frontend:
